### ISSUE TITLE
Porting lib Tags give an error durring data gen

### ISSUE THREAD

**Issue by ReinierTheGhost** [Fabricators-of-Create/Porting-Lib#113]
when ever I try to run a data gen for  my mod I get this error from portinglib tags

[20:08:08] [main/INFO] (FabricDataGenHelper) Running data generator for porting_lib_tags
[20:08:08] [main/INFO] (Minecraft) Starting provider: Porting Lib Tags/Tags for minecraft:fluid
[20:08:08] [main/INFO] (Minecraft) Porting Lib Tags/Tags for minecraft:fluid finished after 0 ms
[20:08:08] [main/INFO] (Minecraft) Starting provider: Porting Lib Tags/Tags for minecraft:block
[20:08:08] [main/INFO] (Minecraft) Porting Lib Tags/Tags for minecraft:block finished after 21 ms
[20:08:08] [main/INFO] (Minecraft) Starting provider: Porting Lib Tags/Tags for minecraft:item
[20:08:08] [main/ERROR] (FabricDataGenHelper) Failed to run data generation
 java.lang.RuntimeException: Failed to run data generator from mod (porting_lib_tags)
	at net.fabricmc.fabric.impl.datagen.FabricDataGenHelper.runInternal(FabricDataGenHelper.java:150) ~[fabric-data-generation-api-v1-12.3.3+d7b148e077.jar:?]
	at net.fabricmc.fabric.impl.datagen.FabricDataGenHelper.run(FabricDataGenHelper.java:89) ~[fabric-data-generation-api-v1-12.3.3+d7b148e077.jar:?]
	at net.minecraft.server.Main.handler$zjl000$fabric-data-generation-api-v1$main(Main.java:1535) ~[minecraft-merged-a185f253c3-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.server.Main.main(Main.java:120) ~[minecraft-merged-a185f253c3-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.9.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) ~[dev-launch-injector-0.2.1+build.8.jar:?]
Caused by: java.util.concurrent.CompletionException: java.lang.NullPointerException: Pass Block tag provider via constructor to use copy
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:687) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662) ~[?:?]
	at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2168) ~[?:?]
	at net.minecraft.data.server.tag.TagProvider.getRegistryLookupFuture(TagProvider.java:103) ~[minecraft-merged-a185f253c3-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.data.server.tag.TagProvider.run(TagProvider.java:90) ~[minecraft-merged-a185f253c3-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.data.DataCache.run(DataCache.java:95) ~[minecraft-merged-a185f253c3-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.data.DataGenerator.method_46563(DataGenerator.java:49) ~[minecraft-merged-a185f253c3-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.data.DataGenerator.run(DataGenerator.java:42) ~[minecraft-merged-a185f253c3-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.fabricmc.fabric.impl.datagen.FabricDataGenHelper.runInternal(FabricDataGenHelper.java:145) ~[fabric-data-generation-api-v1-12.3.3+d7b148e077.jar:?]
	... 7 more
Caused by: java.lang.NullPointerException: Pass Block tag provider via constructor to use copy
	at java.util.Objects.requireNonNull(Objects.java:233) ~[?:?]
	at net.fabricmc.fabric.api.datagen.v1.provider.FabricTagProvider$ItemTagProvider.copy(FabricTagProvider.java:170) ~[fabric-data-generation-api-v1-12.3.3+d7b148e077.jar:?]
	at io.github.fabricators_of_create.porting_lib.tags.data.ItemTagProvider.configure(ItemTagProvider.java:26) ~[tags-2.1.1127+1.20.jar:?]
	at net.minecraft.data.server.tag.TagProvider.method_49706(TagProvider.java:105) ~[minecraft-merged-a185f253c3-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662) ~[?:?]
	at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2168) ~[?:?]
	at net.minecraft.data.server.tag.TagProvider.getRegistryLookupFuture(TagProvider.java:103) ~[minecraft-merged-a185f253c3-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.data.server.tag.TagProvider.run(TagProvider.java:90) ~[minecraft-merged-a185f253c3-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.data.DataCache.run(DataCache.java:95) ~[minecraft-merged-a185f253c3-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.data.DataGenerator.method_46563(DataGenerator.java:49) ~[minecraft-merged-a185f253c3-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.data.DataGenerator.run(DataGenerator.java:42) ~[minecraft-merged-a185f253c3-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.fabricmc.fabric.impl.datagen.FabricDataGenHelper.runInternal(FabricDataGenHelper.java:145) ~[fabric-data-generation-api-v1-12.3.3+d7b148e077.jar:?]
	... 7 more

Process finished with exit code -1

**Comment by IThundxr** [comment]
Add `-Dfabric-api.datagen.modid=<yourmodidhere>` to your runData run configuration

**Comment by VityaSchel** [comment]
> -Dfabric-api.datagen.modid=<

thank you it worked!
for me (I'm working in vscode) I had this config in .vscode/launch.json:

```json
{
      "type": "java",
      "name": "Data Generation",
      "request": "launch",
      "cwd": "${workspaceFolder}/build/datagen",
      "console": "integratedTerminal",
      "stopOnEntry": false,
      "mainClass": "net.fabricmc.devlaunchinjector.Main",
      "vmArgs": "-Dfabric.dli.config\u003d/Users/hloth/Documents/demoviostuff-v2/.gradle/loom-cache/launch.cfg -Dfabric.dli.env\u003dclient -Dfabric-api.datagen -Dfabric-api.datagen.output-dir\u003d/Users/hloth/Documents/demoviostuff-v2/src/main/generated -XstartOnFirstThread -Dfabric.dli.main\u003dnet.fabricmc.loader.impl.launch.knot.KnotClient",
      "args": "",
      "env": {},
      "projectName": "demoviostuff-v2"
    },
```

so as you can see it uses `\u003d` instead of `=`. I added `-Dfabric-api.datagen.modid\u003ddemoviostuff` (`demoviostuff` is my mod_id) and it worked!!!

final result:

```json
{
      "type": "java",
      "name": "Data Generation",
      "request": "launch",
      "cwd": "${workspaceFolder}/build/datagen",
      "console": "integratedTerminal",
      "stopOnEntry": false,
      "mainClass": "net.fabricmc.devlaunchinjector.Main",
      "vmArgs": "-Dfabric.dli.config\u003d/Users/hloth/Documents/demoviostuff-v2/.gradle/loom-cache/launch.cfg -Dfabric.dli.env\u003dclient -Dfabric-api.datagen -Dfabric-api.datagen.output-dir\u003d/Users/hloth/Documents/demoviostuff-v2/src/main/generated -Dfabric-api.datagen.modid\u003ddemoviostuff -XstartOnFirstThread -Dfabric.dli.main\u003dnet.fabricmc.loader.impl.launch.knot.KnotClient",
      "args": "",
      "env": {},
      "projectName": "demoviostuff-v2"
    },
```

**Comment by VityaSchel** [comment]
No idea why but it stopped working for me. Tried clearing cache, removing .gradle, .idea, .run, run
