### ISSUE TITLE
[1.19.2] Porting Lib incompatibility with Fabric Pin Lib

### ISSUE THREAD

**Issue by lxly9** [Fabricators-of-Create/Porting-Lib#33]
As outlined in another issue Porting Lib's map rendering code conflicts with Pin Lib (which adds map pins for waystones), leading to a crash on startup. 

[PinLib](#) is conflicting with [Porting Lib Base](https://github.com/Fabricators-of-Create/Porting-Lib).

## Stacktrace
```
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("LOAD" ordinal=0 index=-1) on net/minecraft/class_330$class_331::pinlib$CheckForCustomMarker with priority 1000 cannot inject into net/minecraft/class_330$class_331::method_1777(Lnet/minecraft/class_4587;Lnet/minecraft/class_4597;ZI)V merged by io.github.fabricators_of_create.porting_lib.mixin.client.MapRendererMapInstanceMixin with priority 1000 [PREINJECT Applicator Phase -> pinlib.mixins.json:MapTextureMixin from mod pinlib -> Prepare Injections ->  -> localvar$hjk000$pinlib$CheckForCustomMarker(Lnet/minecraft/class_20;)Lnet/minecraft/class_20; -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305)
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1338)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at net.fabricmc.loader.impl.launch.knot.MixinServiceKnot.findClass(MixinServiceKnot.java:96)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.audit(MixinProcessor.java:254)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.audit(MixinTransformer.java:171)
	at org.spongepowered.asm.mixin.MixinEnvironment.audit(MixinEnvironment.java:1425)
	at ca.fxco.memoryleakfix.MemoryLeakFix.forceLoadAllMixinsAndClearSpongePoweredCache(MemoryLeakFix.java:30)
	at net.minecraft.client.main.Main.handler$glb000$loadAllMixinsThenShouldRenderAsync(Main.java:526)
	at net.minecraft.client.main.Main.method_44604(Main.java:220)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)

```

## Mod list
```
- additionaladditions 5.1.0
- additionz 1.1.3
- advanced_runtime_resource_pack 0.6.2 via extrasounds
- advdebug 2.3.0
- adventurez 1.4.17
- amecsapi 1.3.7+mc22w17a via mousewheelie
- appleskin 2.4.1+mc1.19
- archeology 0.2.4
- architectury 6.4.62
- auditory 0.0.4-1.19.x
- balm-fabric 4.5.2+0
- beaconoverhaul 1.7.3+1.19.2
- bedbenefits 9.1.2
- beekeeperhut 1.2.0
- bendy-lib 2.1.3-test2 via emotecraft
- better_bad_omen 1.6.0
- bettercombat 1.5.4+1.19
- betterdeserttemples 1.19.2-Fabric-2.2.1
- betterdungeons 1.19.2-Fabric-3.2.1
- betterlily 1.1.0
- bettermounthud 1.2.0
- betteroceanmonuments 1.19.2-Fabric-2.1.0
- betterstrongholds 1.19.2-Fabric-3.2.0
- betterthirdperson 1.9.0
- betterwitchhuts 1.19.2-Fabric-2.1.0
- biomemakeover 1.19.2-1.6.2
- blockstoparts 0.3.0+1.19.2 via vanilla_parts
- blossom 1.0.6
- blue_endless_jankson 1.2.1 via owo
- bookshelf 16.2.17
- borderlessmining 1.1.5+1.19
- bosses_of_mass_destruction 1.4.6-1.19.2
- brainierbees 1.3
- brewinandchewin fabric-1.0.5+1.19.2
- bushierflowers 0.0.1-1.19.2
- c2me 0.2.0+alpha.9.0
- c2me-base 0.2.0+alpha.9.0 via c2me
- c2me-client-uncapvd 0.2.0+alpha.9.0 via c2me
- c2me-fixes-chunkio-threading-issues 0.2.0+alpha.9.0 via c2me
- c2me-fixes-general-threading-issues 0.2.0+alpha.9.0 via c2me
- c2me-fixes-worldgen-threading-issues 0.2.0+alpha.9.0 via c2me
- c2me-fixes-worldgen-vanilla-bugs 0.2.0+alpha.9.0 via c2me
- c2me-notickvd 0.2.0+alpha.9.0 via c2me
- c2me-opts-allocs 0.2.0+alpha.9.0 via c2me
- c2me-opts-chunk-access 0.2.0+alpha.9.0 via c2me
- c2me-opts-chunkio 0.2.0+alpha.9.0 via c2me
- c2me-opts-math 0.2.0+alpha.9.0 via c2me
- c2me-opts-scheduling 0.2.0+alpha.9.0 via c2me
- c2me-opts-worldgen-general 0.2.0+alpha.9.0 via c2me
- c2me-opts-worldgen-vanilla 0.2.0+alpha.9.0 via c2me
- c2me-rewrites-chunkio 0.2.0+alpha.9.0 via c2me
- c2me-server-utils 0.2.0+alpha.9.0 via c2me
- c2me-threading-chunkio 0.2.0+alpha.9.0 via c2me
- c2me-threading-lighting 0.2.0+alpha.9.0 via c2me
- c2me-threading-scheduling 0.2.0+alpha.9.0 via c2me
- c2me-threading-worldgen 0.2.0+alpha.9.0 via c2me
- caffeineconfig 1.0.0+1.17 via sodium-extra
- cameraoverhaul 1.4.0-fabric-universal
- cardinal-components-base 5.0.2 via enchancement
- cardinal-components-block 5.0.2 via puzzleslib
- cardinal-components-chunk 5.0.2 via puzzleslib
- cardinal-components-entity 5.0.2 via enchancement
- cardinal-components-level 5.0.2 via villagernames
- cardinal-components-world 5.0.2 via enchancement
- carpet-layers 1.0.1
- carpeted 1.19.2-1.3
- charm 4.4.4
- charmofundying 6.1.1+1.19.2
- chat_heads 0.9.0
- chime 1.3.0
- chunksfadein 3.0.7-1.19
- cicada 0.1.1 via showmeyourskin
- clear-skies 2.0.95
- clickadv 3.0
- cloth-basic-math 0.6.1 via cloth-config
- cloth-config 8.2.88
- clumps 9.0.0+14
- coat 1.0.0-beta.19+mc22w17a via completeconfig
- collective 6.32
- colorfulenchantments 1.1.1+fabric_1.19.2
- com_electronwill_night-config_core 3.6.6 via corgilib
- com_electronwill_night-config_toml 3.6.6 via corgilib
- com_eliotlash_mclib_mclib 20 via geckolib3
- com_github_llamalad7_mixinextras 0.1.1 via beekeeperhut
- com_ibm_async_asyncutil 0.1.0 via c2me
- com_logisticscraft_occlusionculling 0.0.6-SNAPSHOT via entityculling
- com_moandjiezana_toml_toml4j 0.7.2 via charm
- completeconfig 2.1.0
- completeconfig-base 2.1.0 via completeconfig
- completeconfig-gui-cloth 2.1.0 via completeconfig
- completeconfig-gui-coat 2.1.0 via completeconfig
- completeconfig-gui-yacl 2.1.0 via completeconfig
- conditional-mixin 0.3.0 via cull-less-leaves
- connectiblechains 2.1.4+1.19.2
- continuity 2.0.1+1.19
- controlling 10.0+7
- corgilib 1.0.0.16
- crawl 0.11.1
- creativecore 2.9.3
- creaturesfromthesnow 4.1.0+1.19.2
- creeperoverhaul 2.0.6
- crops_love_rain 1.3.0
- cull-less-leaves 1.0.6
- culturaldelights 0.14.9+1.19.2
- customportalapi 0.0.1-beta54-1.19 via deeperdarker
- customsplashscreen 1.2.0
- darkmodeeverywhere 1.19.2-1.0.4
- dawn 3.5.0
- debugify 2.8.0
- deeperdarker 1.1.6
- disable_custom_worlds_advice 3.0
- doodads 0.1.2-1.19.2
- draggable-resource-packs 3.0.1+build.9
- dragonfight 1.19.2-2.6
- droplight 1.0.5
- dungeon_now_loading 1.0.0
- dynamicfps 2.2.0
- eatinganimationid 1.9
- echoplus 0.1.2
- ecologics 2.1.11
- emi 0.6.1+1.19.2
- emicompat 2.0.2
- emiffect 0.1.4+1.19.2
- emitrades 1.0.2+mc1.19.2
- emotecraft 2.2.7-b.build.47
- enchancement 1.19-10
- enchantmentcompat 1.0.1
- enchdesc 13.0.14
- endrem 5.2.0
- enhanced_attack_indicator 1.0.4+1.19
- entity_texture_features 4.3.1
- entityculling 1.5.2-mc1.19
- expandeddelight 0.2.2
- extrasounds 2.3.1+1.19.2-1.19.1
- fabric-api 0.73.0+1.19.2
- fabric-api-base 0.4.14+6e0787e690 via fabric-api
- fabric-api-lookup-api-v1 1.6.13+93d8cb8290 via fabric-api
- fabric-biome-api-v1 9.1.0+82db024a90 via fabric-api
- fabric-block-api-v1 1.0.2+e415d50e90 via fabric-api
- fabric-blockrenderlayer-v1 1.1.23+c6af733c90 via fabric-api
- fabric-client-tags-api-v1 1.0.4+b35fea8390 via fabric-api
- fabric-command-api-v1 1.2.15+f71b366f90 via fabric-api
- fabric-command-api-v2 2.2.0+413cbbc790 via fabric-api
- fabric-commands-v0 0.2.32+df3654b390 via fabric-api
- fabric-containers-v0 0.1.40+df3654b390 via fabric-api
- fabric-content-registries-v0 3.5.0+7c6cd14d90 via fabric-api
- fabric-convention-tags-v1 1.2.1+27265b3490 via fabric-api
- fabric-crash-report-info-v1 0.2.8+aeb40ebe90 via fabric-api
- fabric-data-generation-api-v1 5.3.6+413cbbc790 via fabric-api
- fabric-dimensions-v1 2.1.34+0d0f210290 via fabric-api
- fabric-entity-events-v1 1.5.3+9244241690 via fabric-api
- fabric-events-interaction-v0 0.4.33+562bff6e90 via fabric-api
- fabric-events-lifecycle-v0 0.2.34+df3654b390 via fabric-api
- fabric-game-rule-api-v1 1.0.24+b6b6abb490 via fabric-api
- fabric-item-api-v1 1.6.4+693ffc0590 via fabric-api
- fabric-item-groups-v0 0.3.37+9244241690 via fabric-api
- fabric-key-binding-api-v1 1.0.25+5c4fce2890 via fabric-api
- fabric-keybindings-v0 0.2.23+df3654b390 via fabric-api
- fabric-language-kotlin 1.9.0+kotlin.1.8.0
- fabric-lifecycle-events-v1 2.2.3+1b46dc7890 via fabric-api
- fabric-loot-api-v2 1.1.11+83a8659290 via fabric-api
- fabric-loot-tables-v1 1.1.14+9e7660c690 via fabric-api
- fabric-message-api-v1 5.0.6+93d8cb8290 via fabric-api
- fabric-mining-level-api-v1 2.1.22+33fbc73890 via fabric-api
- fabric-models-v0 0.3.20+c6af733c90 via fabric-api
- fabric-networking-api-v1 1.2.10+10eb22f490 via fabric-api
- fabric-networking-v0 0.3.27+df3654b390 via fabric-api
- fabric-object-builder-api-v1 4.2.0+d8ef690890 via fabric-api
- fabric-particles-v1 1.0.13+4d0d570390 via fabric-api
- fabric-permissions-api-v0 0.1-SNAPSHOT via spark
- fabric-recipe-api-v1 1.0.0+413cbbc790 via fabric-api
- fabric-registry-sync-v0 0.9.31+9244241690 via fabric-api
- fabric-renderer-api-v1 1.2.0+2e5408b590 via fabric-api
- fabric-renderer-indigo 0.7.0+2e5408b590 via fabric-api
- fabric-renderer-registries-v1 3.2.23+df3654b390 via fabric-api
- fabric-rendering-data-attachment-v1 0.3.18+6e0787e690 via fabric-api
- fabric-rendering-fluids-v1 3.0.10+4d0d570390 via fabric-api
- fabric-rendering-v0 1.1.26+df3654b390 via fabric-api
- fabric-rendering-v1 1.12.0+d8ef690890 via fabric-api
- fabric-resource-conditions-api-v1 2.1.2+aae9039d90 via fabric-api
- fabric-resource-loader-v0 0.8.3+251d254a90 via fabric-api
- fabric-screen-api-v1 1.0.31+4d0d570390 via fabric-api
- fabric-screen-handler-api-v1 1.3.6+1cc24b1b90 via fabric-api
- fabric-sound-api-v1 1.0.2+c4f28df590 via fabric-api
- fabric-textures-v0 1.0.23+aeb40ebe90 via fabric-api
- fabric-transfer-api-v1 2.1.5+413cbbc790 via fabric-api
- fabric-transitive-access-wideners-v1 1.3.3+08b73de490 via fabric-api
- fabricloader 0.14.13
- farmersdelight 1.19.2-1.3.9
- farmersknives 2.4
- farmersrespite 2.2.2
- ferritecore 5.0.3
- flowers 1.0.0
- forge_tags 3.0 via porting_lib
- forgeconfigapiport 4.2.10
- forgetmechunk 1.0.4-1.18.X-1.19.X
- frame 0.26.1+1.19-fabric
- frame-api-base 0.2.1+906ebc04a9 via frame
- frame-blocks-v0 0.1.3+233e7428a9 via frame
- frame-config-v0 0.3.1+0fa45150a9 via frame
- frame-content-registries-v0 0.4.0+2876b511a9 via frame
- frame-enchantments-v0 0.1.0+4093105da9 via frame
- frame-game-rules-v0 0.2.4+e7ce56a6a9 via frame
- frame-items-v0 0.1.3+906ebc04a9 via frame
- frame-loot-tables-v0 0.1.4+4f7341eca9 via frame
- frame-registries-v0 0.1.1+0e0ec74ea9 via frame
- frame-rendering-v0 0.1.5+906ebc04a9 via frame
- frame-tabbed-item-groups-v0 0.2.4+0aca9b56a9 via frame
- frame-toymaker-v0 0.6.1+b13741c3a9 via frame
- frame-woods-v0 0.2.1+6a33fbada9 via frame
- friendsandfoes 1.6.7
- frozenlib 1.1.8-Fabric+1.19.2-unstable
- fwaystones 3.0.5+mc1.19.2
- geckolib3 3.1.38
- geodes 1.6.3
- globalpacks 1.14.3.1_fabric
- handcrafted 2.0.2
- herdspanic 1.0.6
- highlighter 1.1.4
- iceberg 1.0.46
- immediatelyfast 1.1.7
- immersive_weathering 1.19.2-1.2.5
- impaled 1.1.4
- indium 1.0.9+mc1.19.2
- ingredient-extension-api 3.0.6
- io_github_douira_glsl-transformer 2.0.0-pre8 via iris
- iris 1.5.0
- itemmodelfix 1.0.3+1.19
- jankson 4.1.1+j1.2.1 via libgui
- java 17
- keymap 0.7.0-beta.1+1.19.2-fabric
- kirin 1.11.0 via voidfog
- kubejs 1902.6.0-build.140
- labels 1.19.2-1.7
- lambdabettergrass 1.3.0+1.19
- lambdynlights 2.2.0+1.19.2
- langfiles-plus 1.0.0 via cicada
- lazydfu 0.1.3
- legendarytooltips 1.3.3
- libblockattributes_core 0.11.1 via libmultipart_deps_container
- libgui 6.0.0-beta.5+1.19-pre1 via additionaladditions
- libmultipart 0.8.0 via libmultipart_deps_container
- libmultipart_deps_container 0.8.0 via vanilla_parts
- libnetworkstack 0.7.1 via libmultipart_deps_container
- libninepatch 1.1.0 via libgui
- lithium 0.10.4
- lootjs 2.7.8
- maelstrom_library 1.3-1.19-pre1 via bosses_of_mass_destruction
- map_atlases 2.3.1
- mavapi 1.0.1
- mavm 1.2.0
- memoryleakfix 1.19.1-0.7.0
- midnightlib 1.0.0 via enchancement
- minecarttweaks 1.6
- minecraft 1.19.2
- mixin-conflict-helper 1.2.0
- mixintrace 1.1.1+1.17
- mm 2.3 via crawl
- modmenu 4.1.2
- moonlight 1.19.2-2.1.30
- moreculling 1.19.1-0.14.0
- morefrogs 1.19.x-1.2.3-fabric
- moremcmeta 1.19-3.0.5
- moremobvariants 1.0.0
- mousetweaks 2.22
- mousewheelie 1.10.7+mc1.19.2
- multipart_entities 1.2-1.19-pre1 via bosses_of_mass_destruction
- naturalist 2.1.1
- nbtcrafting 2.2.3+mc1.19 via wilderwild
- net_objecthunter_exp4j 0.4.8 via c2me
- netherdepthsupgrade fabric-2.0.3
- nethermap 2.0.2-1.19.2
- nethersdelight 1.0.1
- nicer-skies 1.2.0
- no-resource-pack-warnings 1.0.0
- no-telemetry 1.5.0
- nochatreports 1.19.2-v1.13.12
- norecipebook 2.2+1.19
- notenoughanimations 1.6.2
- numismatic-overhaul 0.2.8+1.19
- onsoulfire 1.19-2
- org_anarres_jcpp 1.4.14 via iris
- org_antlr_antlr4-runtime 4.11.1 via iris
- org_apache_httpcomponents_httpmime 4.5.10 via entity_texture_features
- org_javassist_javassist 3.28.0-GA via yungsapi
- org_jetbrains_kotlin_kotlin-reflect 1.8.0 via fabric-language-kotlin
- org_jetbrains_kotlin_kotlin-stdlib 1.8.0 via fabric-language-kotlin
- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.8.0 via fabric-language-kotlin
- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.8.0 via fabric-language-kotlin
- org_jetbrains_kotlinx_atomicfu-jvm 0.18.5 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.4.1 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.4.1 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.4.1 via fabric-language-kotlin
- org_joml_joml 1.10.4 via sodium
- org_reflections_reflections 0.10.2 via yungsapi
- org_threadly_threadly 7.0 via c2me
- org_yaml_snakeyaml 1.27 via paragon
- overweight_farming 1.19.2-2.0.2-fabric
- owo 0.9.3+1.19
- oxidized 1.7.2
- paginatedadvancements 1.1.0-1.19
- paragon 3.0.2 via deeperdarker
- pinlib 0.2.0+1.19
- player-animator 0.4.2-test0
- playerabilitylib 1.6.0 via overweight_farming
- porting_lib 2.1.623+1.19.2 via farmersrespite
- porting_lib_accessors 2.1.623+1.19.2 via porting_lib_extensions
- porting_lib_attributes 2.1.623+1.19.2 via porting_lib_extensions
- porting_lib_base 2.1.623+1.19.2 via porting_lib
- porting_lib_common 2.1.623+1.19.2 via porting_lib_extensions
- porting_lib_constants 2.1.623+1.19.2 via porting_lib_attributes
- porting_lib_entity 2.1.623+1.19.2 via porting_lib
- porting_lib_extensions 2.1.623+1.19.2 via porting_lib_transfer
- porting_lib_lazy_registration 2.1.623+1.19.2 via porting_lib
- porting_lib_model_generators 2.1.623+1.19.2 via porting_lib
- porting_lib_model_loader 2.1.623+1.19.2 via porting_lib_obj_loader
- porting_lib_models 2.1.623+1.19.2 via porting_lib
- porting_lib_networking 2.1.623+1.19.2 via porting_lib
- porting_lib_obj_loader 2.1.623+1.19.2 via porting_lib
- porting_lib_transfer 2.1.623+1.19.2 via porting_lib
- pride 1.1.2+1.19 via lambdynlights
- prism 1.0.3
- profundis 1.4.1
- puzzle 1.4.2-1.19
- puzzle-base 1.4.2-1.19 via puzzle
- puzzle-gui 1.4.2-1.19 via puzzle
- puzzle-models 1.4.2-1.19 via puzzle
- puzzle-splashscreen 1.4.2-1.19 via puzzle
- puzzleslib 4.3.12
- raised 1.1.4
- reach-entity-attributes 2.3.0 via beaconoverhaul
- reeses-sodium-options 1.4.9+mc1.19.2-build.67
- rhino 1902.2.2-build.264
- rottencreatures 1.0.1
- roundalib 0.2.1 via enchantmentcompat
- scout 1.1.2
- screenshotclipboard 1.0.9
- serialization_hooks 0.3.26 via porting_lib_base
- showmeyourskin 1.3.7+1.19
- shulkerboxtooltip 3.2.2+1.19.2
- skinlayers 1.5.2-mc1.19.1
- sleepwarp 1.2.0+1.19
- slimyboyos 5.0.0.5
- smarterfarmers 1.19.2-1.7.0
- smoothboot 1.19-1.7.1
- sneaky 1.1
- sodium 0.4.4+build.18
- sodium-extra 0.4.16+mc1.19.2-build.90
- sound_physics_remastered 1.19.2-1.0.18
- soundcategories 1.2.4+1.19 via extrasounds
- spark 1.10.17
- sparkle 1.0.3
- spelunkery 1.19.2-0.1.4
- spirit-walker 0.1.1+1.19
- spruceui 4.1.0+1.19.2 via lambdynlights
- stacc 1.3.3 via numismatic-overhaul
- starlight 1.1.1+fabric.ae22326
- step-height-entity-attribute 1.0.0 via enchancement
- structory 1.0.1
- summoningrituals 1.19.2-2.0.2
- supplementaries 1.19.2-2.2.41
- t_and_t 1.10
- takesapillage 1.0.4
- talkbubbles 1.0.4
- team_reborn_energy 2.0.0-beta1 via emicompat
- terraform-wood-api-v1 4.2.0 via culturaldelights
- tooltipfix 1.1.1-1.19
- torohealth 1.19-fabric-1
- totw_additions 1.2.3
- travelerstitles 1.19.2-Fabric-3.1.0
- trinkets 3.4.2
- trinkets-curios-theme 0.2.2+1.19
- tweed4_annotated 1.3.1+mc22w17a via mousewheelie
- tweed4_base 1.7.1+mc22w17a via mousewheelie
- tweed4_data 1.2.1+mc22w17a via mousewheelie
- tweed4_data_hjson 1.1.1+mc22w17a via mousewheelie
- tweed4_tailor_coat 1.1.3+mc22w17a via mousewheelie
- tweed4_tailor_screen 1.1.3+mc22w17a via mousewheelie
- twigs 2.0.0-beta.9+1.19-fabric
- universal_ores 1.4.2
- vanilla_parts 2.1.0+1.19.2
- variant_bookshelves 1.2.4
- variantbarrels 2.4.5
- variantcraftingtables 3.2.9
- villagernames 4.0.8
- vinery 1.1.4
- visuality 0.5.5
- visualworkbench 4.2.1
- voidfog 2.7.1
- wandering_collector 1.1.3+mc1.19
- wardenloot 1.0.9-1.19.x
- wardentools 2.1.2
- waterdripsound 1.19-0.3.0
- wilderwild 1.1.7-Fabric+1.19.2
- yet-another-config-lib 1.7.1
- yungsapi 1.19.2-Fabric-3.8.2
- yungsbridges 1.19.2-Fabric-3.1.0
- yungsextras 1.19.2-Fabric-3.1.0
- zoomglass 1.1
```

## Game info
Minecraft Version: 1.19.2
Fabric Loader Version: 0.14.13

*Message autogenerated using [MixinConflictHelper](https://github.com/isXander/MixinConflictHelper)*

**Comment by TropheusJ** [comment]
Already fixed in newer versions

**Comment by lxly9** [comment]
oh, then the few mods that arent compatible anymore use an older version perhaps!
