### ISSUE TITLE
Compat issue with Twillight Forest

### ISSUE THREAD

**Issue by rdrpenguin04** [Fabricators-of-Create/Porting-Lib#38]
Hello! I see another report last year of a crash, and the solution was removing Twilight Forest. The question is, can this be fixed?

```
---- Minecraft Crash Report ----
// I blame Dinnerbone.
Time: 2023-02-06 20:28:49
Description: Initializing game
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'twilightforest'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:459)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
Caused by: java.lang.NullPointerException: Registry Object not present: twilightforest:antibuilder
	at java.base/java.util.Objects.requireNonNull(Objects.java:334)
	at io.github.fabricators_of_create.porting_lib.util.RegistryObject.get(RegistryObject.java:66)
	at twilightforest.init.TFBlockEntities.lambda$static$0(TFBlockEntities.java:22)
	at io.github.fabricators_of_create.porting_lib.util.LazyRegistrar.lambda$register$0(LazyRegistrar.java:67)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
	at io.github.fabricators_of_create.porting_lib.util.LazyRegistrar.register(LazyRegistrar.java:66)
	at twilightforest.TwilightForestMod.onInitialize(TwilightForestMod.java:90)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 11 more
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:459)
-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Linux (amd64) version 6.1.9-zen1-2-zen
	Java Version: 17.0.6, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 265421432 bytes (253 MiB) / 1161822208 bytes (1108 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 5700U with Radeon Graphics
	Identifier: AuthenticAMD Family 23 Model 104 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: Lucienne
	Graphics card #0 vendor: Advanced Micro Devices, Inc. [AMD/ATI] (0x1002)
	Graphics card #0 VRAM (MB): 258.00
	Graphics card #0 deviceId: 0x164c
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 24052.91
	Virtual memory used (MB): 9981.93
	Swap memory total (MB): 16383.00
	Swap memory used (MB): 2499.25
	JVM Flags: 2 total; -Xms512m -Xmx4096m
```
The above seems to be the relevant part of the log, and it seems directly related to an interaction between PortingLib and Twighlight Forest. Is there anything that I or someone else can do to help resolve this?

**Comment by TropheusJ** [comment]
it will be fixed in the next TF update

**Comment by rdrpenguin04** [comment]
Alright, thank you! :D
